/**
 * ملف المحتوى المركزي — جميع البيانات مستخرجة من السيرة الذاتية (CV) فقط
 * All content is extracted faithfully from the attached CV — nothing invented.
 */

export type Lang = "ar" | "en";

export const ui = {
  ar: {
    nav: {
      home: "الرئيسية",
      about: "عني",
      ai: "الذكاء الاصطناعي",
      data: "البيانات",
      design: "التصميم",
      experience: "المسيرة",
      credentials: "الاعتمادات",
      contact: "تواصل",
    },
    hero: {
      name: "أفنان",
      fullName: "أفنان فهد الجهني",
      title: "مهندسة ذكاء اصطناعي",
      taglineEn: "Building intelligent solutions where technology meets creativity.",
      taglineAr: "أبني حلولًا ذكية حيث تلتقي التقنية بالإبداع.",
      motto: "Engineering Intelligence. Designing Possibilities.",
      ctaWork: "استكشف أعمالي",
      ctaAbout: "عني",
      available: "متاحة للفرص المهنية",
    },
    explore: {
      label: "معرض الأعمال",
      title: "استكشف أعمالي",
      subtitle: "كل مجال هو قاعة عرض مستقلة — ادخل واستكشف",
      enter: "ادخل المعرض",
      folders: [
        {
          id: "ai",
          index: "01",
          title: "الذكاء الاصطناعي",
          titleEn: "Artificial Intelligence",
          desc: "تعلم عميق، رؤية حاسوبية، ونماذج تعلم آلة",
          count: "مشروعان",
          href: "/work/ai",
        },
        {
          id: "data",
          index: "02",
          title: "تحليل البيانات",
          titleEn: "Data Analytics",
          desc: "لوحات مؤشرات، ذكاء أعمال، وسرد البيانات",
          count: "٣ أعمال",
          href: "/work/data",
        },
        {
          id: "design",
          index: "03",
          title: "التصميم الإبداعي",
          titleEn: "Creative Design",
          desc: "استوديو التصميم: واجهات، جرافيك، وهوية بصرية",
          count: "٦ مجالات",
          href: "/work/design",
        },
        {
          id: "software",
          index: "04",
          title: "البرمجيات والتقنية",
          titleEn: "Software & Technology",
          desc: "هياكل بيانات، خوارزميات، وهندسة أنظمة",
          count: "مسار هندسي",
          href: "/work/software",
        },
      ],
    },
    about: {
      index: "01",
      label: "من أنا",
      title: "عني",
      blocks: [
        {
          key: "who",
          title: "من أنا",
          text: "خريجة علوم حاسب بمرتبة الشرف من جامعة جدة، مسار علوم البيانات، مع إعداد تقني متقدم من مدرسة هولبرتون وأكاديمية طويق.",
        },
        {
          key: "what",
          title: "ماذا أبني",
          text: "أطوّر خطوط معالجة للرؤية الحاسوبية، وأحسّن بنى تعلم الآلة، وأبني تدفقات بيانات عملية ولوحات مؤشرات تنفيذية تفاعلية.",
        },
        {
          key: "care",
          title: "ما يهمني",
          text: "تحويل البيانات المعقدة إلى رؤى واضحة قابلة لاتخاذ القرار، وبناء حلول تقنية منظمة قابلة للتوسع.",
        },
        {
          key: "where",
          title: "حيث تلتقي التقنية بالإبداع",
          text: "لا أستخدم التقنية لبناء النماذج فحسب، بل لصناعة تجارب وحلول وأفكار بصرية — من نماذج التعلم العميق إلى تصميم الواجهات والهويات البصرية.",
        },
      ],
      stats: [
        { value: "24K+", label: "صورة طبية في مشروع التخرج" },
        { value: "3", label: "نماذج تعلم عميق تمت مقارنتها" },
        { value: "15+", label: "شهادة واعتمادًا احترافيًا" },
        { value: "4", label: "خبرات تدريبية ومهنية" },
      ],
    },
    identity: {
      index: "02",
      label: "الهوية",
      title: "حيث يلتقي الذكاء الاصطناعي بالإبداع",
      titleEn: "Where AI Meets Creativity",
      roles: ["مهندسة ذكاء اصطناعي", "عالمة بيانات", "مصممة إبداعية"],
      center: "AFNAN",
      text: "أستخدم التقنية ليس فقط لبناء النماذج، بل لصناعة تجارب وحلول وأفكار بصرية.",
    },
    journey: {
      index: "03",
      label: "المسيرة المهنية",
      title: "رحلتي",
      subtitle: "التعليم والخبرات والتدريب بترتيب زمني",
      items: [
        {
          type: "experience",
          org: "Outstanding Knowledge Consultancy",
          role: "متدربة ذكاء اصطناعي وبيانات",
          period: "يناير 2026 — مايو 2026",
          desc: "بناء نماذج تنبؤية وأتمتة إجراءات إعداد البيانات باستخدام Python و SQL لدعم مشاريع استشارية تقنية موجهة للعملاء.",
          contribution: "تحويل منطق الأعمال التشغيلي إلى تدفقات بيانات منظمة وقابلة للتوسع بالتعاون مع فرق هندسية متعددة التخصصات.",
        },
        {
          type: "experience",
          org: "Holberton School — أكاديمية طويق",
          role: "متدربة هندسة برمجيات متقدمة",
          period: "فبراير 2026 — أغسطس 2026",
          desc: "منهج هجين صارم يجمع بين التعاون الميداني المكثف وهندسة المشاريع عن بُعد، مع حلول تصميم برمجية لتحديات هندسية واقعية وهياكل بيانات وخوارزميات معقدة.",
          contribution: "التعلم النظير المتقدم ومراجعات الكود النشطة تحت إشراف خبراء الصناعة، مع إتقان أساسات علوم الحاسب وتطبيقات هندسة البيانات.",
        },
        {
          type: "experience",
          org: "الهيئة العامة للطيران المدني (GACA)",
          role: "تدريب تعاوني — ذكاء اصطناعي وبيانات",
          period: "فبراير 2026 — أبريل 2026",
          desc: "إنشاء لوحات مؤشرات تفاعلية شاملة في Power BI و Tableau لمراقبة مؤشرات الأداء المؤسسية ودعم اتخاذ القرار التنفيذي، ومعالجة مجموعات بيانات طيران واسعة النطاق.",
          contribution: "تطبيق معايير حوكمة البيانات المؤسسية لضمان المعالجة الآمنة وحماية الخصوصية عبر الأصول البيانية الداخلية.",
        },
        {
          type: "education",
          org: "جامعة جدة",
          role: "بكالوريوس علوم الحاسب — مسار علوم البيانات",
          period: "2026",
          desc: "خريجة بمرتبة الشرف، مع شهادة إتمام المسار المالي من كلية الأعمال بجامعة جدة.",
          contribution: "مشروع تخرج بحثي: خط تعلم عميق لتصنيف الصور الطبية (DermaVision).",
        },
        {
          type: "experience",
          org: "الهيئة السعودية للبيانات والذكاء الاصطناعي (SDAIA)",
          role: "متدربة تحليل بيانات",
          period: "يوليو 2022 — أكتوبر 2022",
          desc: "إدارة خطوط إعداد البيانات من البداية إلى النهاية: معالجة القيم المفقودة وتوحيد التعارضات الهيكلية عبر مجموعات بيانات متعددة المصادر.",
          contribution: "تحليل البيانات التاريخية لكشف الاتجاهات وتقديم تقارير أداء واضحة لأصحاب المصلحة الرئيسيين.",
        },
      ],
    },
    tech: {
      index: "04",
      label: "الترسانة التقنية",
      title: "Tech Stack",
      categories: [
        {
          title: "الذكاء الاصطناعي وتعلم الآلة",
          titleEn: "AI & Machine Learning",
          skills: ["Python", "PyTorch", "TensorFlow", "Keras", "Scikit-learn", "Deep Learning", "Computer Vision", "CNNs", "Vision Transformers", "Feature Engineering", "ML Pipelines"],
        },
        {
          title: "البيانات",
          titleEn: "Data",
          skills: ["SQL", "MySQL", "PostgreSQL", "Data Analysis", "EDA", "Power BI", "Tableau", "Data Storytelling"],
        },
        {
          title: "التطوير",
          titleEn: "Development",
          skills: ["Git", "GitHub", "Linux (Red Hat)", "System Analysis", "Technical Documentation"],
        },
        {
          title: "الإبداع",
          titleEn: "Creative",
          skills: ["Figma", "Canva", "UI/UX Design", "Graphic Design", "Presentation Design", "Interior Design"],
        },
      ],
      languagesTitle: "اللغات",
      languages: [
        { name: "العربية", level: "لغة أم" },
        { name: "الإنجليزية", level: "متقدمة" },
      ],
      attributes: ["التعاون النظير", "حل المشكلات القائم على المشاريع", "تحليل الأنظمة", "التوثيق التقني"],
    },
    credentials: {
      index: "05",
      label: "قبو الاعتمادات",
      title: "الشهادات والإنجازات",
      subtitle: "اضغط على أي شهادة لعرض التفاصيل",
      awardsTitle: "الجوائز والهاكاثونات",
      certsTitle: "الشهادات الاحترافية",
      issuer: "الجهة",
      year: "السنة",
      type: "النوع",
      awardType: "جائزة / هاكاثون",
      certType: "شهادة احترافية",
      awards: [
        {
          title: "الشهادة الذهبية+ — Kanz AI Hackathon 2026",
          issuer: "Supercharge Your Data Analytics with Generative AI",
          year: "يوليو 2026",
          highlight: true,
        },
        {
          title: "المركز الثاني — Snap AR Lens Challenge",
          issuer: "Saudi Digital Academy × Snapchat",
          year: "2026",
          highlight: true,
        },
      ],
      certs: [
        { title: "HCIA-AI 4.0", issuer: "Huawei Cloud Middle East", year: "2026" },
        { title: "HCIA-IoT V3.0", issuer: "Huawei Cloud Middle East", year: "2026" },
        { title: "HCIA OpenEuler V1", issuer: "Huawei Cloud Middle East", year: "2026" },
        { title: "Student Ambassador Program", issuer: "IBM SkillsBuild", year: "مايو 2026" },
        { title: "AI Accelerator Program", issuer: "King Saud University — Industrial Engineering Club", year: "2026" },
        { title: "Increase Productivity & Improve Efficiency", issuer: "SDAIA", year: "أغسطس 2026" },
        { title: "Data Analysis Virtual Work Experience", issuer: "STC × Misk Foundation", year: "مارس 2026" },
        { title: "Fundamentals of Artificial Intelligence", issuer: "SDAIA", year: "2025" },
        { title: "Data Engineering Foundation", issuer: "SDAIA", year: "2023" },
        { title: "RH124 — Red Hat System Administration I", issuer: "Red Hat", year: "2023" },
        { title: "Database and SQL for Data Science with Python", issuer: "IBM", year: "2022" },
        { title: "Python Project for Data Engineering", issuer: "IBM", year: "2022" },
        { title: "Introduction to Relational Databases (RDBMS)", issuer: "Coursera", year: "2022" },
      ],
    },
    contact: {
      index: "06",
      label: "لنبنِ شيئًا ذكيًا معًا",
      title: "لنبنِ شيئًا ذكيًا معًا",
      titleEn: "Let's Build Something Intelligent",
      subtitle: "هل لديك مشروع أو فرصة؟ يسعدني التواصل.",
      email: "البريد الإلكتروني",
      phone: "الجوال",
      location: "الموقع",
      locationValue: "الرياض، المملكة العربية السعودية",
      cta: "لنتواصل",
      whatsappLabel: "واتساب",
      whatsappCta: "تواصل عبر واتساب",
      whatsappNote: "رد سريع خلال ساعات العمل",
    },
    footer: {
      made: "صُنع بشغف",
      by: "أفنان فهد الجهني",
      rights: "© 2026",
    },
    back: "العودة للرئيسية",
    backToWork: "كل المعارض",
    project: {
      problem: "التحدي",
      solution: "الحل",
      role: "دوري",
      tech: "التقنيات",
      results: "النتائج",
      type: "نوع المشروع",
      contribution: "المساهمة الجوهرية",
    },
  },
  en: {
    nav: {
      home: "Home",
      about: "About",
      ai: "AI",
      data: "Data",
      design: "Design",
      experience: "Experience",
      credentials: "Credentials",
      contact: "Contact",
    },
    hero: {
      name: "AFNAN",
      fullName: "Afnan Fahad Aljohani",
      title: "AI Engineer",
      taglineEn: "Building intelligent solutions where technology meets creativity.",
      taglineAr: "أبني حلولًا ذكية حيث تلتقي التقنية بالإبداع.",
      motto: "Engineering Intelligence. Designing Possibilities.",
      ctaWork: "Explore My Work",
      ctaAbout: "About Me",
      available: "Open to opportunities",
    },
    explore: {
      label: "Exhibition of Work",
      title: "Explore My Work",
      subtitle: "Each domain is an independent exhibition room — step in and explore",
      enter: "Enter Exhibition",
      folders: [
        {
          id: "ai",
          index: "01",
          title: "Artificial Intelligence",
          titleEn: "الذكاء الاصطناعي",
          desc: "Deep learning, computer vision & machine learning models",
          count: "2 projects",
          href: "/work/ai",
        },
        {
          id: "data",
          index: "02",
          title: "Data Analytics",
          titleEn: "تحليل البيانات",
          desc: "Dashboards, business intelligence & data storytelling",
          count: "3 works",
          href: "/work/data",
        },
        {
          id: "design",
          index: "03",
          title: "Creative Design",
          titleEn: "التصميم الإبداعي",
          desc: "My creative studio: UI/UX, graphics & visual identity",
          count: "6 domains",
          href: "/work/design",
        },
        {
          id: "software",
          index: "04",
          title: "Software & Technology",
          titleEn: "البرمجيات والتقنية",
          desc: "Data structures, algorithms & systems engineering",
          count: "Engineering track",
          href: "/work/software",
        },
      ],
    },
    about: {
      index: "01",
      label: "Who I Am",
      title: "About Me",
      blocks: [
        {
          key: "who",
          title: "Who I am",
          text: "An honors Computer Science graduate from the University of Jeddah, Data Science track, with advanced technical preparation from Holberton School and Tuwaiq Academy.",
        },
        {
          key: "what",
          title: "What I build",
          text: "I develop computer vision pipelines, optimize machine learning architectures, and build practical data workflows and interactive executive dashboards.",
        },
        {
          key: "care",
          title: "What I care about",
          text: "Turning complex data into clear, decision-ready insights, and engineering structured, scalable technical solutions.",
        },
        {
          key: "where",
          title: "Where technology meets creativity",
          text: "I use technology not only to build models, but to craft experiences, solutions, and visual ideas — from deep learning models to interface and identity design.",
        },
      ],
      stats: [
        { value: "24K+", label: "Medical images in graduation project" },
        { value: "3", label: "Deep learning models benchmarked" },
        { value: "15+", label: "Professional certifications" },
        { value: "4", label: "Professional & training roles" },
      ],
    },
    identity: {
      index: "02",
      label: "Identity",
      title: "Where AI Meets Creativity",
      titleEn: "Where AI Meets Creativity",
      roles: ["AI Engineer", "Data Scientist", "Creative Designer"],
      center: "AFNAN",
      text: "I use technology not only to build models — but to craft experiences, solutions, and visual ideas.",
    },
    journey: {
      index: "03",
      label: "Professional Journey",
      title: "My Journey",
      subtitle: "Education, experience and training in chronological order",
      items: [
        {
          type: "experience",
          org: "Outstanding Knowledge Consultancy",
          role: "AI and Data Intern",
          period: "January 2026 — May 2026",
          desc: "Built predictive models and automated data preparation procedures using Python and SQL to support client-facing technical consulting projects.",
          contribution: "Worked alongside cross-functional engineering teams to transform operational business logic into structured, scalable data workflows.",
        },
        {
          type: "experience",
          org: "Holberton School (by Tuwaiq Academy)",
          role: "Advanced Software Engineering Trainee",
          period: "February 2026 — August 2026",
          desc: "Selected for a prestigious, rigorous hybrid curriculum of intensive on-site peer collaboration and continuous remote project engineering — building software design solutions for real-world challenges, complex data structures, and algorithms.",
          contribution: "Advanced peer-to-peer learning and active code reviews under structured industry mentorship, with dual exposure across CS foundations and data engineering applications.",
        },
        {
          type: "experience",
          org: "General Authority of Civil Aviation (GACA)",
          role: "Co-op Training — AI and Data",
          period: "February 2026 — April 2026",
          desc: "Created comprehensive interactive dashboards in Power BI and Tableau to monitor corporate KPIs and support executive decision-making, handling large-scale aviation datasets with thorough EDA and data cleansing in Python.",
          contribution: "Applied enterprise data governance standards to maintain secure handling and privacy protection across internal data assets.",
        },
        {
          type: "education",
          org: "University of Jeddah",
          role: "B.Sc. Computer Science — Data Science Track",
          period: "2026",
          desc: "Honors graduate, with a Certificate of Completion — Finance Track, College of Business, University of Jeddah.",
          contribution: "Graduation research project: Deep Learning Pipeline for Image Classification (DermaVision).",
        },
        {
          type: "experience",
          org: "Saudi Data and AI Authority (SDAIA)",
          role: "Data Analysis Trainee",
          period: "July 2022 — October 2022",
          desc: "Managed end-to-end data preparation pipelines, fixing missing values and standardizing structural inconsistencies across multi-source datasets.",
          contribution: "Analyzed historical data to identify underlying trends, delivering clear performance reports to key organization stakeholders.",
        },
      ],
    },
    tech: {
      index: "04",
      label: "Tech Stack",
      title: "Tech Stack",
      categories: [
        {
          title: "AI & Machine Learning",
          titleEn: "الذكاء الاصطناعي وتعلم الآلة",
          skills: ["Python", "PyTorch", "TensorFlow", "Keras", "Scikit-learn", "Deep Learning", "Computer Vision", "CNNs", "Vision Transformers", "Feature Engineering", "ML Pipelines"],
        },
        {
          title: "Data",
          titleEn: "البيانات",
          skills: ["SQL", "MySQL", "PostgreSQL", "Data Analysis", "EDA", "Power BI", "Tableau", "Data Storytelling"],
        },
        {
          title: "Development",
          titleEn: "التطوير",
          skills: ["Git", "GitHub", "Linux (Red Hat)", "System Analysis", "Technical Documentation"],
        },
        {
          title: "Creative",
          titleEn: "الإبداع",
          skills: ["Figma", "Canva", "UI/UX Design", "Graphic Design", "Presentation Design", "Interior Design"],
        },
      ],
      languagesTitle: "Languages",
      languages: [
        { name: "Arabic", level: "Native" },
        { name: "English", level: "Advanced" },
      ],
      attributes: ["Peer-to-Peer Collaboration", "Project-Based Problem Solving", "System Analysis", "Technical Documentation"],
    },
    credentials: {
      index: "05",
      label: "Certificate Vault",
      title: "Credentials & Achievements",
      subtitle: "Click any certificate to view details",
      awardsTitle: "Awards & Hackathons",
      certsTitle: "Professional Certifications",
      issuer: "Issuer",
      year: "Year",
      type: "Type",
      awardType: "Award / Hackathon",
      certType: "Professional Certification",
      awards: [
        {
          title: "Gold Certificate+ — Kanz AI Hackathon 2026",
          issuer: "Supercharge Your Data Analytics with Generative AI",
          year: "July 2026",
          highlight: true,
        },
        {
          title: "2nd Place — Snap AR Lens Challenge",
          issuer: "Saudi Digital Academy × Snapchat",
          year: "2026",
          highlight: true,
        },
      ],
      certs: [
        { title: "HCIA-AI 4.0", issuer: "Huawei Cloud Middle East", year: "2026" },
        { title: "HCIA-IoT V3.0", issuer: "Huawei Cloud Middle East", year: "2026" },
        { title: "HCIA OpenEuler V1", issuer: "Huawei Cloud Middle East", year: "2026" },
        { title: "Student Ambassador Program", issuer: "IBM SkillsBuild", year: "May 2026" },
        { title: "AI Accelerator Program", issuer: "King Saud University — Industrial Engineering Club", year: "2026" },
        { title: "Increase Productivity & Improve Efficiency", issuer: "SDAIA", year: "August 2026" },
        { title: "Data Analysis Virtual Work Experience", issuer: "STC × Misk Foundation", year: "March 2026" },
        { title: "Fundamentals of Artificial Intelligence", issuer: "SDAIA", year: "2025" },
        { title: "Data Engineering Foundation", issuer: "SDAIA", year: "2023" },
        { title: "RH124 — Red Hat System Administration I", issuer: "Red Hat", year: "2023" },
        { title: "Database and SQL for Data Science with Python", issuer: "IBM", year: "2022" },
        { title: "Python Project for Data Engineering", issuer: "IBM", year: "2022" },
        { title: "Introduction to Relational Databases (RDBMS)", issuer: "Coursera", year: "2022" },
      ],
    },
    contact: {
      index: "06",
      label: "Let's Connect",
      title: "Let's Build Something Intelligent",
      titleEn: "Let's Build Something Intelligent",
      subtitle: "Have a project or an opportunity? I'd love to hear from you.",
      email: "Email",
      phone: "Phone",
      location: "Location",
      locationValue: "Riyadh, Saudi Arabia",
      cta: "Let's Connect",
      whatsappLabel: "WhatsApp",
      whatsappCta: "Chat on WhatsApp",
      whatsappNote: "Fast reply during working hours",
    },
    footer: {
      made: "Crafted with passion",
      by: "Afnan Fahad Aljohani",
      rights: "© 2026",
    },
    back: "Back to Home",
    backToWork: "All Exhibitions",
    project: {
      problem: "Problem",
      solution: "Solution",
      role: "My Role",
      tech: "Technologies",
      results: "Results",
      type: "Project Type",
      contribution: "Key Contribution",
    },
  },
};

export const contactData = {
  email: "a.almass3dii@gmail.com",
  phone: "+966 54 537 9819",
  phoneHref: "tel:+966545379819",
  whatsapp: "https://wa.me/966545379819",
  whatsappDisplay: "+966 54 537 9819",
  linkedin: "https://www.linkedin.com/in/afnan-fahad-aljohani-0b5a70315/",
  linkedinDisplay: "linkedin.com/in/afnan-fahad-aljohani",
};
